"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tpz%8o*f=ryppw3ztx@#%a34qbh&1=@z$#vk+hjsapexccx-g9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- REGISTRO DE DEPENDÊNCIAS E APPS (AULA 17) ---
    'rest_framework',   # Aula 17: Adicionado Django REST Framework 
    'drf_spectacular',  # Aula 17: Adicionado DRF Spectacular para documentação OpenAPI 
    'django_filters',   # Aula 17: Adicionado Django Filter 
    'produtos',         # Aula 17: Adicionado o App 'produtos' 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# --- INTERNACIONALIZAÇÃO E FUSO HORÁRIO (AULA 17) ---
LANGUAGE_CODE = 'pt-br'            # Aula 17: Idioma ajustado para Português do Brasil 
TIME_ZONE = 'America/Sao_Paulo'    # Aula 17: Fuso horário ajustado para o Brasil 

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# --- CONFIGURAÇÕES DO DRF, SWAGGER E FILTROS (AULA 20) ---
REST_FRAMEWORK = {  # Aula 20: Dicionario de configuracoes do REST Framework 
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # Aula 20: Define o gerador de esquema OpenAPI 
    'DEFAULT_FILTER_BACKENDS': (  # Aula 20: Tupla de backends de filtro padrao 
        'django_filters.rest_framework.DjangoFilterBackend',  # Alteração: Habilita suporte ao django-filter 
    ),  # Aula 20: Fechamento da tupla de backends 
}  # Aula 20: Fechamento do dicionario REST_FRAMEWORK 

SPECTACULAR_SETTINGS = {  # Aula 20: Dicionario de informacoes da documentacao Swagger 
    'TITLE': 'API de Gestão de Produtos',  # Aula 20: Titulo exibido no Swagger 
    'DESCRIPTION': 'Documentacao interativa da API desenvolvida no curso',  # Aula 20: Descricao da API 
    'VERSION': '1.0.0',  # Aula 20: Versao da API 
    'SERVE_INCLUDE_SCHEMA': False,  # Aula 20: Oculta a rota do esquema bruto na interface do Swagger 
}  # Aula 20: Fechamento do dicionario SPECTACULAR_SETTINGS 